name: REDIS_DEPLOYMENT

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Redis Container with Custom User Authentication
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} bash -c "
            if sudo docker inspect -f '{{.State.Running}}' redis-cache &>/dev/null; then
              sudo docker stop redis-cache && sudo docker rm redis-cache
            fi
            # Create ACL file
            echo \"# Disable default user
            user default off
            # Create custom user with full access
            user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ~* +@all\" > /tmp/redis-users.acl

            # Ensure the ACL file exists before running Docker
            touch /tmp/redis-users.acl

            # Deploy Redis container
            sudo docker run -d \
              --name redis-cache \
              -p 6379:6379 \
              -v /tmp/redis-users.acl:/usr/local/etc/redis-users.acl \
              redis:latest \
              redis-server --aclfile /usr/local/etc/redis-users.acl
          "
        env:
          REDIS_USERNAME: ${{ vars.REDIS_USERNAME }}
          REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}
