name: REDIS_DEPLOYMENT

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host to Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Redis Container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} "
            if sudo docker inspect -f '{{.State.Running}}' redis-cache &>/dev/null; then
              sudo docker stop redis-cache && sudo docker rm redis-cache
            fi
            sudo docker run -d \
              --name redis-cache \
              -p 6379:6379 \
              redis:latest \
              redis-server --requirepass $REDIS_PASSWORD
          "
        env:
          REDIS_PASSWORD: ${{ vars.REDIS_PASSWORD }}

